### ISSUE TITLE
[Request] Add Commit Support

### ISSUE THREAD

**Issue by Herculezz55** [SethCohen/github-releases-to-discord#30]
would it be possible to add commit support, and extraction from the 2 tags, maybe by craping the full change log link /shrug?

**Comment by Herculezz55** [comment]
or even maybe from each PR link and have each commit from each pr underneath in a bulleted list. all pretty just like the PR part

**Comment by SethCohen** [comment]
Do you have a visual example of more exactly what you mean? Because from my understanding, the action already had commit support.
![image](https://github.com/user-attachments/assets/2e2691b8-41cf-4683-85fa-b60cff051250)

**Comment by Herculezz55** [comment]
well here you can see its only showing the PR's in my release but not the commits, but TBH i think this is more of a generate release notes issue because your app just goes off whats in the Release notes
![Screenshot 2024-10-10 195816](https://github.com/user-attachments/assets/9e0bad8f-5225-4372-8133-47ed1e3433fd)
![Screenshot 2024-10-10 195841](https://github.com/user-attachments/assets/ce23aadd-0763-48f0-9298-86e17bf59098)

**Comment by SethCohen** [comment]
> i think this is more of a generate release notes issue because your app just goes off whats in the Release notes 

Yeah, that is correct. This Action only really reposts your release notes into your designated discord channel.
It doesn't actually check or scrape for commit history, PRs, etc. It simply just sends whatever is in your Release Notes.

If you'd like, I'd heavily recommend checking out [Google's Release Please](https://github.com/googleapis/release-please) as it will auto-generate releases with commit-support release notes. Or, if you're using a different script to manage releases, you'd have to manually modify that to create release notes that link to each specific commit. Sadly, implementing what you're asking is out-of-scope for this action and takes away from this action's main goal. Sorry
