### ISSUE TITLE
GitHub link parsing changes in v1.15.1

### ISSUE THREAD

**Issue by drichar** [SethCohen/github-releases-to-discord#32]
I've noticed an issue after upgrading from v1.15.0 to v1.15.1 of the `github-releases-to-discord` action. Link parsing is no longer functioning as expected.

v1.15.0
<img width="604" alt="image" src="https://github.com/user-attachments/assets/6b9e723a-8ddb-4867-b186-3a702905be37">

v1.15.1
<img width="603" alt="image" src="https://github.com/user-attachments/assets/a5812ba5-d0b8-42b4-9721-f106bf156628">

Previously, links to pull requests, commits, compare diffs, etc. were shortened in the generated Discord message. However, in the latest version, these links are appearing in their full form. Was this an intended change?

Additionally, while converting @ mentions to user profile links is a great enhancement, it's being applied too broadly. The package names in my release notes are being incorrectly parsed as links.

To resolve this I'll be submitting a PR that refines the regex pattern used for @ mentions to only match valid GitHub usernames.

Thank you for your time. Love the action and appreciate you building and maintaining it!

**Comment by SethCohen** [comment]
It wasn't an intended change, but whilst refactoring the code, I must've accidentally deleted the implementation. I've reimplemented this functionality in a cleaner way (07c2e1c) — should work based off my testing. Feel free to always provide any feedback, open any additional issues, or submit any PRs if ever needed. Thanks for bringing this to notice🙂

**Comment by drichar** [comment]
Works great now, thank you so much for fixing and for merging my PR!
